package com.mouceu.floatingtouch;

enum SlideAction {
    OPEN_RECENT_APPS,
    OPEN_NOTIFICATIONS,
    OPEN_HOME_SCREEN,
    OPEN_PREVIOUS_APP,
    GO_BACK,
    OPEN_POWER_DIALOG,
    OPEN_QUICK_SETTINGS,
    TOGGLE_SPLIT_SCREEN,
    NONE
}